#!/bin/bash -x
echo "Welcome to Flip Coin Simulation Program"

tails=0;
heads=0;
TossCheck=$((RANDOM%2));
if [ $TossCheck -eq 0 ];
then
	tails=$(($tails+1));
	echo Tails Win;
else
	heads=$(($heads+1));
	echo Heads Win;
fi

done

echo "Number of times Tails won: "$tails

echo "Number of times Heads won: "$heads

if [ $heads -gt $tails ]
then
	echo "Heads won by: "$(( $heads-$tails ));

else
	echo "Tails won by: "$(( $tails-$heads ));

fi

done

echo "Tails count: "$tails "and Heads count :"$heads;O

